---
title: "PyData Workshop - plotnine"
output: 
  flexdashboard::flex_dashboard:
    theme: united
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

PyData Workshop
=====================

Column {.tabset}
--------------

### plotnine
<h4>plotnine</h4>
plotnine started as an effort to improve the scaling functionality in ggpy formally known as "ggplot for python". It was part of a larger goal to evolve the package into one that supported a full plotting grammar. It turned out that to have a grammar of graphics system we had to just about start anew.
<p>
The complete guide to what constitutes a "Grammar of Graphics" is Leland Wilkinson's book The Grammar of Graphics. To create ggplot2 Hadley Wickham came up with an interpretation termed A layered grammar of graphics 1. 
<p>
Core to the interpretation is a crucial plot building pipeline 2 in ggplot2 that we adopted 3 for plotnine.

<p>
The R programming language has a rich statistical ecosystem that ggplot2 taps into with ease. In plotnine we have done our best to integrate with the rest of the scientific python ecosystem. Though we feel we could do more on that integration, notwithstanding language differences, users familiar with ggplot2 should be comfortable and productive with plotnine.
<p>

---------------------------

Built with

* matplotlib - Plotting backend.
* pandas - Data handling.
* mizani - Scales framework.
* statsmodels - For various statistical computations.
* scipy - For various statistical computation procedures.


---------------------------
1
The Grammar of Graphics has to be interpreted into a form that can be implemented. We were not up to this task.

2
This is more or less an implementation of what is depicted in Figure 2.2 of The Grammar of Graphics

3
By adopting a similar pipeline and user API as ggplot2 the other internals referenced within the pipeline look similar.


### Tutorual

Manipulating date breaks and date labels
import pandas as pd
import numpy as np

from plotnine import *
from plotnine.data import economics

from mizani.breaks import date_breaks
from mizani.formatters import date_format

theme_set(theme_linedraw()) # default theme

%matplotlib inline
Using the economics dataset

```{Python eval=FALSE}
economics.head()
```

<pre><code>
date	pce	pop	psavert	uempmed	unemploy
0	1967-07-01	507.4	198712	12.5	4.5	2944
1	1967-08-01	510.5	198911	12.5	4.7	2945
2	1967-09-01	516.3	199113	11.7	4.6	2958
3	1967-10-01	512.9	199311	12.5	4.9	3143
4	1967-11-01	518.1	199498	12.5	4.7	3066
</code></pre>

How does the saving rate vary with time?

(ggplot(economics)
 + geom_point(aes('date', 'psavert'))
 + labs(y='personal saving rate')
)
../_images/tutorials_miscellaneous-manipulating-date-breaks-and-date-labels_5_0.png
<ggplot: (97654321012345679)>
Yikes! the calculated breaks are awful, we need to intervene. We do so using the date_breaks and date_format functions from mizani.

Set breaks every 10 years

(ggplot(economics)
 + geom_point(aes('date', 'psavert'))
 + scale_x_datetime(breaks=date_breaks('10 years'))        # new
 + labs(y='personal saving rate')
)
../_images/tutorials_miscellaneous-manipulating-date-breaks-and-date-labels_7_0.png
<ggplot: (97654321012345679)>
That is better. Since all the breaks are at the beginning of the year, we can omit the month and day. Using date_format we override the format string. For more on the options for the format string see the strftime behavior.


(ggplot(economics)
 + geom_point(aes('date', 'psavert'))
 + scale_x_datetime(breaks=date_breaks('10 years'), labels=date_format('%Y'))     # modified
 + labs(y='personal saving rate')
)
../_images/tutorials_miscellaneous-manipulating-date-breaks-and-date-labels_9_0.png
<ggplot: (97654321012345679)>
We can achieve the same result with a custom formating function.

def custom_date_format1(breaks):
    """
    Function to format the date
    """
    return [x.year if x.month==1 and x.day==1 else "" for x in breaks]

(ggplot(economics)
 + geom_point(aes('date', 'psavert'))
 + scale_x_datetime(                                # modified
     breaks=date_breaks('10 years'),
     labels=custom_date_format1)
 + labs(y='personal saving rate')
)
../_images/tutorials_miscellaneous-manipulating-date-breaks-and-date-labels_11_0.png
<ggplot: (97654321012345679)>
We can use a custom formatting function to get results that are not obtainable with the date_format function. For example if we have monthly breaks over a handful of years we can mix date formats as follows; specify beginning of the year and every other month. Such tricks can be used reduce overcrowding.

```{python eval=FALSE}
from datetime import date

def custom_date_format2(breaks):
    """
    Function to format the date
    """
    res = []
    for x in breaks:
        # First day of the year
        if x.month == 1 and x.day == 1:
            fmt = '%Y'
        # Every other month
        elif x.month % 2 != 0:
            fmt = '%b'
        else:
            fmt = ''

        res.append(date.strftime(x, fmt))

    return res

(ggplot(economics.loc[40:60, :])                            # modified
 + geom_point(aes('date', 'psavert'))
 + scale_x_datetime(
     breaks=date_breaks('1 months'),
     labels=custom_date_format2,
     minor_breaks=[])
 + labs(y='personal saving rate')
)
```
<ggplot: (97654321012345679)>
We removed the labels but not the breaks, leaving behind dangling ticks for the skipped months. We can fix that by wrapping date_breaks around a filtering function.

```{python eval=FALSE}
def custom_date_format3(breaks):
    """
    Function to format the date
    """
    res = []
    for x in breaks:
        # First day of the year
        if x.month == 1:
            fmt = '%Y'
        else:
            fmt = '%b'

        res.append(date.strftime(x, fmt))

    return res


def custom_date_breaks(width=None):
    """
    Create a function that calculates date breaks

    It delegates the work to `date_breaks`
    """
    def filter_func(limits):
        breaks = date_breaks(width)(limits)
        # filter
        return [x for x in breaks if x.month % 2]

    return filter_func


(ggplot(economics.loc[40:60, :])
 + geom_point(aes('date', 'psavert'))
 + scale_x_datetime(                                        # modified
     breaks=custom_date_breaks('1 months'),
     labels=custom_date_format3)
 + labs(y='personal saving rate')
)
```

The breaks and labels functions are tightly coupled to give us exactly what we want.